- name: installing base programs
  yum: name={{ item }}
  with_items:
    - wget
    - curl
    - zip
    - unzip

- file:
    path: /var/log/journal
    state: directory
    mode: "u=rwx,g=rs,o=rx"

- name: Fix permissions
  command: systemd-tmpfiles --create --prefix /var/log/journal

- name: Restart systemd-journald
  systemd:
    daemon_reload: yes
    name: systemd-journald
    state: restarted

- name: ansible create directory using loops
  file:
    path: "{{ item.dest }}"
    mode: "{{item.mode}}"
    state: directory
  loop:
    - { dest: '/tmp/data/elasticsearch/data', mode: '0777'}
    - { dest: '/tmp/data/grafana', mode: '0777'}
    - { dest: '/tmp/data/mongo', mode: '0777'}
    - { dest: '/tmp/data/splunk/logs', mode: '0777'}
    - { dest: '/tmp/data/nginx/logs', mode: '0777'}
    - { dest: '/tmp/data/prometheus', mode: '0777'}
    - { dest: '/tmp/data/wikijs/logs', mode: '0777'}
    - { dest: '/tmp/data/grafana/provisioning/dashboards', mode: '0777'}
    - { dest: '/tmp/data/grafana/provisioning/datasources', mode: '0777'}   
    - { dest: '/tmp/data/grafana/dashboards', mode: '0777'}
    - { dest: '/var/lib/grafana/dashboards', mode: '0777'}
    - { dest: '/tmp/data/splunk/config', mode: '0777'}

