- name: installing base programs
  yum: name={{ item }}
  with_items:
    - git
    - zip
    - unzip

- git:
    repo: https://github.com/pavlomykytyuk/ansible-aws-docker-elk-prometheus.git
    dest: /tmp/repo
 #   separate_git_dir: /tmp/ansible-examples.git

- name: deploying application
  shell: docker stack deploy -c /tmp/repo/docker-compose.yml pavlo-stack
