- name: installing base programs
  yum: name={{ item }}
  with_items:
    - git
    - zip
    - unzip

- git:
    repo: https://github.com/pavlomykytyuk/ansible-aws-docker-elk-prometheus.git
    dest: /tmp/repo
 #   separate_git_dir: /tmp/ansible-examples.git

- name: Render k8s defs (infra)
  template:
#    remote_src: yes 
    src: "../wiki/config/config.yml.j2"
    dest: "/tmp/repo/wiki/config/config.yml"
    mode: 0644
    remote_src: yes

- name: Render k8s defs (infra)
  template:
#    remote_src: yes
    src: "../prometheus/config/prometheus.yml.j2"
    dest: "/tmp/repo/prometheus/config/prometheus.yml"
    mode: 0644
  

- name: deploying application
  shell: docker stack deploy -c /tmp/repo/docker-compose.yml pavlo-stack
