- name: installing base programs
  yum: name={{ item }}
  loop:
    - git
    - mc
    - nano

- git:
    repo: https://github.com/pavlomykytyuk/ansible-aws-docker-elk-prometheus.git
    dest: /tmp/repo
 #   separate_git_dir: /tmp/ansible-examples.git

- name: Render k8s defs 1 (infra)
  template:
    src: "../wiki/config/config.yml.j2"
    dest: "/tmp/repo/wiki/config/config.yml"
    mode: 0644
#    remote_src: yes

- name: Render k8s defs 2 (infra)
  template:
    src: "../prometheus/config/prometheus.yml.j2"
    dest: "/tmp/repo/prometheus/config/prometheus.yml"
    mode: 0644
#    remote_src: yes  

- name: deploying application
  shell: docker stack deploy -c /tmp/repo/docker-compose.yml pavlomykytyuk-stack
